name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          consumer_key: ${{secrets.GOOGLE_CONSUMER_KEY}}
          consumer_secret: ${{secrets.GOOGLE_CONSUMER_SECRET}}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install google-cloud-language
        pip install TwitterAPI
    - name: Analysing the code with pylint
      run: |
        python senti_analyze.py
        pylint `ls -R|grep .py$|xargs`
